<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-18 at 19:42:21.
 */
require_once ('Book.php');

class BookTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Book
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Book('firstBook');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Book::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        echo $this->object->getName();
    }
}
