<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-18 at 09:16:54.
 */
require_once('SimpleDotCom.php');

class SimpleDotComTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SimpleDotCom
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SimpleDotCom;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SimpleDotCom::setLocationCells
     * @todo   Implement testSetLocationCells().
     */
    public function testSetLocationCells()
    {
        $locs = array(1,3,4);
        $this->object->setLocationCells($locs);
    }

    /**
     * @covers SimpleDotCom::checkYourself
     * @todo   Implement testCheckYourself().
     */
    public function testCheckYourself()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
