<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-19 at 22:57:28.
 */
require_once ('Banner.php');
class BannerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Banner
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Banner('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Banner::showWithParen
     * @todo   Implement testShowWithParen().
     */
    public function testShowWithParen()
    {
        $this->object->showWithParen();
    }

    /**
     * @covers Banner::showWithAster
     * @todo   Implement testShowWithAster().
     */
    public function testShowWithAster()
    {
        $this->object->showWithAster();
    }
}
